language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t minhbh/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true minhbh/react-test npm test

after_success:
    - docker build -t minhbh/multi-client ./client
    - docker build -t minhbh/multi-nginx ./nginx
    - docker build -t minhbh/multi-server ./server
    - docker build -t minhbh/multi-worker ./worker
    # docker login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push minhbh/multi-client
    - docker push minhbh/multi-nginx
    - docker push minhbh/multi-server
    - docker push minhbh/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-149223794690"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY